### ISSUE TITLE
Add simple testing framework for use within curriculum

### ISSUE THREAD

**Issue by dbp** [the-learning-collective/tlcjs#24]
I just realized as I started filling out some of the design recipe content (Ch 3) that we need a way for people to write tests! 

Probably we should either incorporate a really simple unit test framework (if such a framework exists), or develop one (perhaps expanding on the couple lines that I put at the top of `tlc.js`). 

People should be able to write "examples" (ie, tests), and get output if they fail (and total successes/failures probably). console output is probably okay for this? 

And, of course, we need to incorporate it into the sandboxes...

**Comment by aguestuser** [comment]
Agree! I don't think we necessarily need a full-on testing framework though. If we bring the [chai assertions library](http://chaijs.com/api/bdd/) into scope, users should be able to write inline assertions, much like they are encouraged to do in HTDP.

Eg, under this approach we'd encourage students to write something like the following:

``` javascript
// (Number) -> Number 
function addOne(num) { return num + 1 }

addOne(1).should.equal(2);
addOne(0).should.equal(1);
addOne(0).should.equal(0); // <== BOOM! (will throw)
```

Is that sufficient? Is the throwing behavior too disruptive?

**Comment by aguestuser** [comment]
if we want a testing framework, [mocha](http://mochajs.org/) is almost certainly the way to go, except it won't be possible to write the tests inline, and setting them up to run in the browser requires a fair amount of hairy boilerplate to export and import modules via [require.js](http://requirejs.org/).

**Comment by aepyornis** [comment]
It's actually possible to use mocha in the browser without fancy modules or requirejs. You set up the runner html page like such:

``` html
<script src="path/to/mocha"></script>
<script src="path/to/chai/or/another/assertion/library"></script>
<script> mocha.setup() ... </script>
<script src="path/to/YourJavascript"></script>
<script src="path/to/Tests"></script>
<script>
  // or write tests here
</script>
```

Of course, this doesn't modularize code and places everything in global scope, but it still works okay as a simple testing setup.

**Comment by dbp** [comment]
Hmm. We haven't done methods yet, so explaining the .should.equal()
notation might be a bit of a distraction?

On the other hand, we probably need to explain methods really soon, so
perhaps that isn't a bad reason to?

**Comment by aepyornis** [comment]
We could just use basic asserts:

``` javascript
function addOne(num) { return num + 1 }

assert(addOne(2), 3);
assert(addOne(5), 10);
```

This more closely matches how TLC.js operates. Although (for better or worse) it's basically the same as the testEquals function from the chapter you wrote.

**Comment by aguestuser** [comment]
We _could_ use basic asserts. I positively loathe that syntax -- and think the cognitive overhead of grokking it (instead of the fluent syntax of `expect` or `should` paradigms) cuts against trying to convince people that testing can reduce friction rather than increase it... But I recognize it requires introducing methods and that everything else in the code so far is very lispy (which `assert` sort of is)... so I wouldn't block. ;)

**Comment by dbp** [comment]
How about calling the basic function `shouldEqual`? Then, once we introduce methods, we can transition to using `.should.equal()` syntax with (minimal) difference?

**Comment by dbp** [comment]
I added some beginnings of this into tlc.js, which you can see in action in our test file:

http://tlcjs.org/template.html

(at the bottom). 

The idea is that you create some test output at some point (I'd like it at the top of the page, but, ho hum.. anyway). And then you continually update that output. That way, you get a report of what passes, what fails, etc. And I managed to figure out how to get some source location information (may be very brittle).

**Comment by aguestuser** [comment]
@dbp: looks great!  i also particularly appreciate your notes to the testing code! :)

as homework: i'd like to help pull in mocha for "backend" (ie: non-student-facing) code. is there a good subset of the code to use as a foothold? (ie: something already pretty modular, decoupled, lends itself to testing?)

also happy to collaborate on continuing to flesh out the design recipes section (perhaps with some finger exercise examples?) if that would be a better use of time...

**Comment by aguestuser** [comment]
I also like the lesson about objects/functions that stating the equivalence of `shouldEqual(arg, someOtherArg)` and `arg.should.equal(someOtherArg)` sets up. (ie: methods are just functions that implicitly take their context -- `this` -- as their first argument!)

**Comment by dbp** [comment]
Hey @aguestuser - probably the easiest thing to test is the `_type` (and now, `__type`) functions. Then probably the image arithmetic functions (ie, `overlay`, `placeImage`). Not sure after that - testing drawing is hard :)

**Comment by dbp** [comment]
Though I'm actually going to close this issue, because I think we figured out a solution - adding a "library" test suite sounds great, but should be a different issue I think (or just pull request).

**Comment by dbp** [comment]
Oh actually #15 already exists!
