### ISSUE TITLE
Add width, height for images, length for strings

### ISSUE THREAD

**Issue by emhoracek** [the-learning-collective/tlcjs#27]
These would be useful for lots of things, especially graphics.

**Comment by emhoracek** [comment]
Fixed by d30cc73567086e2bd5e4f2f248672cfafeff39e6

**Comment by emhoracek** [comment]
Still need to add examples to the text.

**Comment by dbp** [comment]
I added these in to exercises for ch 3. Is that enough? (and they should go into the reference).

**Comment by emhoracek** [comment]
Added to the reference.
