### ISSUE TITLE
Figure out a way to add 'asides' in text

### ISSUE THREAD

**Issue by dbp** [the-learning-collective/tlcjs#7]
This would be helpful!

**Comment by emhoracek** [comment]
```
[NOTE]
==================
Text of note goes here
==================
```

seems to work.

Reference: 

http://asciidoc.org/userguide.html#X104
http://asciidoc.org/userguide.html#X22

Need to add these to the README....

**Comment by emhoracek** [comment]
AsciiDoc has a sidebar too! (Don't know let if it's styled in EJS.) I added the information to the README.
